from . import res_company
from . import res_config_settings
from . import notification_event
from . import push_service
from . import crm_lead
from . import project_task
from . import sale_order
from . import stock_picking
from . import purchase_order
